### ISSUE TITLE
Give this plugin a proper folder structure

### ISSUE THREAD

**Issue by danielo515** [danielo515/TW5-KeyboardSnippets#6]
This plugin was developed directly on the browser.

That makes maintaining it and updating it a pain. Investing some time splitting it in several files and adapting it to the node.js workflow is definitively a must go.

**Comment by felixhayashi** [comment]
Yes please do so, I wish I could easily use it with nodejs without dragndrop!

Thanks
-Felix

**Comment by danielo515** [comment]
This have been resolved on 6ce36817b2b9482544bd7ef9ef6445abd0f67259

**Comment by felixhayashi** [comment]
Yes! Many thanks @danielo515 for taking care of this!

**Comment by danielo515** [comment]
Should I expect some pull request @felixhayashi  ? :tongue:

**Comment by felixhayashi** [comment]
> Should I expect some pull request

Well I didn't plan any at the moment but you never know ;)

**Comment by felixhayashi** [comment]
But now with your new repo structure and name, we can better promote your plugin!

**Comment by danielo515** [comment]
Indeed! Promotion is as important as developing!
